
package com.knure.project.server.service;

import com.filmcatalog.movies.Movie;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 *
 */
@WebService(name = "MovieService", targetNamespace = "http://service.server.project.knure.com/")
@XmlSeeAlso({
    com.filmcatalog.movies.ObjectFactory.class,
    com.knure.project.server.service.ObjectFactory.class
})
public interface MovieService {


    /**
     *
     * @param author
     * @param parameters
     * @return
     *     returns com.knure.project.server.service.GetAllMoviesByAuthorResponse
     */
    @WebMethod
    @WebResult(name = "getAllMoviesByAuthorResponse", targetNamespace = "http://service.server.project.knure.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.server.project.knure.com/MovieService/getAllMoviesByAuthorRequest", output = "http://service.server.project.knure.com/MovieService/getAllMoviesByAuthorResponse")
    public GetAllMoviesByAuthorResponse getAllMoviesByAuthor(
        @WebParam(name = "getAllMoviesByAuthor", targetNamespace = "http://service.server.project.knure.com/", partName = "parameters")
        GetAllMoviesByAuthor parameters,
        @WebParam(name = "author", targetNamespace = "http://service.server.project.knure.com/", header = true, partName = "author")
        Movie.Author author);

    /**
     *
     * @param movie
     * @return
     *     returns int
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovie", targetNamespace = "http://service.server.project.knure.com/", className = "com.knure.project.server.service.AddMovie.movie")
    @ResponseWrapper(localName = "addMovieResponse", targetNamespace = "http://service.server.project.knure.com/", className = "com.knure.project.server.service.AddMovieResponse")
    @Action(input = "http://service.server.project.knure.com/MovieService/addMovieRequest", output = "http://service.server.project.knure.com/MovieService/addMovieResponse", fault = {
            @FaultAction(className = DAOException_Exception.class, value = "http://service.server.project.knure.com/MovieService/addMovie/Fault/DAOException")
    })
    public Movie addMovie(
            @WebParam(name = "movie", targetNamespace = "http://service.server.project.knure.com/")
            Movie movie)
            throws DAOException_Exception
    ;

    /**
     *
     * @param clientToken
     * @param id
     * @param parameters
     * @param serverToken
     * @return
     *     returns com.knure.project.server.service.RemoveMovieResponse
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(name = "removeMovieResponse", targetNamespace = "http://service.server.project.knure.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.server.project.knure.com/MovieService/removeMovieRequest", output = "http://service.server.project.knure.com/MovieService/removeMovieResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://service.server.project.knure.com/MovieService/removeMovie/Fault/DAOException")
    })
    public RemoveMovieResponse removeMovie(
        @WebParam(name = "removeMovie", targetNamespace = "http://service.server.project.knure.com/", partName = "parameters")
        RemoveMovie parameters,
        @WebParam(name = "id", targetNamespace = "http://service.server.project.knure.com/", header = true, partName = "id")
        int id,
        @WebParam(name = "clientToken", targetNamespace = "http://service.server.project.knure.com/", header = true, partName = "clientToken")
        SecurityHeader clientToken,
        @WebParam(name = "serverToken", targetNamespace = "http://service.server.project.knure.com/", header = true, mode = WebParam.Mode.OUT, partName = "serverToken")
        Holder<String> serverToken)
        throws DAOException_Exception
    ;

    /**
     *
     * @param id
     * @param parameters
     * @return
     *     returns com.knure.project.server.service.GetMovieByIdResponse
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(name = "getMovieByIdResponse", targetNamespace = "http://service.server.project.knure.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.server.project.knure.com/MovieService/getMovieByIdRequest", output = "http://service.server.project.knure.com/MovieService/getMovieByIdResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://service.server.project.knure.com/MovieService/getMovieById/Fault/DAOException")
    })
    public GetMovieByIdResponse getMovieById(
        @WebParam(name = "getMovieById", targetNamespace = "http://service.server.project.knure.com/", partName = "parameters")
        GetMovieById parameters,
        @WebParam(name = "id", targetNamespace = "http://service.server.project.knure.com/", header = true, partName = "id")
        int id)
        throws DAOException_Exception
    ;

    /**
     *
     * @param movieID
     * @param parameters
     * @return
     *     returns com.knure.project.server.service.ChangeMovieNameResponse
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(name = "changeMovieNameResponse", targetNamespace = "http://service.server.project.knure.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.server.project.knure.com/MovieService/changeMovieNameRequest", output = "http://service.server.project.knure.com/MovieService/changeMovieNameResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://service.server.project.knure.com/MovieService/changeMovieName/Fault/DAOException")
    })
    public ChangeMovieNameResponse changeMovieName(
        @WebParam(name = "changeMovieName", targetNamespace = "http://service.server.project.knure.com/", partName = "parameters")
        ChangeMovieName parameters,
        @WebParam(name = "movieID", targetNamespace = "http://service.server.project.knure.com/", header = true, partName = "movieID")
        int movieID)
        throws DAOException_Exception
    ;

}
